import { Button, Heading, HStack, Input, Stack, Grid, Flex, Text } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import { libCep } from './api/libCep'

interface DataProps {
  bairro: string,
  cep: string,
  complemento: string,
  ddd: string,
  gia: string,
  ibge: string,
  localidade: string,
  logradouro: string,
  siafi: string,
  uf: string, 
}

const Home: NextPage = () => {

  const [ value, setValue ] = useState<string>("");
  const [ data, setData ] = useState<DataProps>();

  async function main() {
    try {
      const response = await libCep.getAddress(value);
      setData(response)
      console.log(response)
    }
    catch(err: any){
      console.log(err.message)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Stack spacing="2rem" justify="center" alignItems="center">
          <Heading
            bgGradient='linear(to-l, #7928CA, #FF0080)'
            bgClip='text'
            fontSize='6xl'
          >
            ViaCEP
          </Heading>
          <HStack>
            <Input
              type="text" 
              value={value}
              onChange={(e: any) => setValue(e.target.value)}
            />
            <Button
              onClick={() => main()}
            >
              Buscar
            </Button>
          </HStack>
          {data && (
            <Grid
              templateColumns="repeat(4, 1fr)"
              gap="1rem"
              w="600px"
              bgColor="gray.100"
              padding="20px"
              borderRadius="5px"
              textAlign="center"
            >
              <Stack>
                <Heading
                  fontSize="1rem"
                  fontWeight="bold"
                  textTransform="uppercase"
                >
                  bairro
                </Heading>
                <Text>
                  {data?.bairro} 
                </Text>
              </Stack>

              <Stack>
                <Heading
                  fontSize="1rem"
                  fontWeight="bold"
                  textTransform="uppercase"
                >
                  cep
                </Heading>
                <Text>
                  {data?.cep} 
                </Text>
              </Stack>

              <Stack>
                <Heading
                  fontSize="1rem"
                  fontWeight="bold"
                  textTransform="uppercase"
                >
                  complemento
                </Heading>
                <Text>
                  {data?.complemento} 
                </Text>
              </Stack>

              <Stack>
                <Heading
                  fontSize="1rem"
                  fontWeight="bold"
                  textTransform="uppercase"
                >
                  ddd
                </Heading>
                <Text>
                  {data?.ddd} 
                </Text>
              </Stack>

              <Stack>
                <Heading
                  fontSize="1rem"
                  fontWeight="bold"
                  textTransform="uppercase"
                >
                  gia
                </Heading>
                <Text>
                  {data?.gia} 
                </Text>
              </Stack>

              <Stack>
                <Heading
                  fontSize="1rem"
                  fontWeight="bold"
                  textTransform="uppercase"
                >
                  ibge
                </Heading>
                <Text>
                  {data?.ibge} 
                </Text>
              </Stack>

              <Stack>
                <Heading
                  fontSize="1rem"
                  fontWeight="bold"
                  textTransform="uppercase"
                >
                  localidade
                </Heading>
                <Text>
                  {data?.localidade} 
                </Text>
              </Stack>

              <Stack>
                <Heading
                  fontSize="1rem"
                  fontWeight="bold"
                  textTransform="uppercase"
                >
                  logradouro
                </Heading>
                <Text>
                  {data?.logradouro} 
                </Text>
              </Stack>

              <Stack>
                <Heading
                  fontSize="1rem"
                  fontWeight="bold"
                  textTransform="uppercase"
                >
                  siafi
                </Heading>
                <Text>
                  {data?.siafi} 
                </Text>
              </Stack>

              <Stack>
                <Heading
                  fontSize="1rem"
                  fontWeight="bold"
                  textTransform="uppercase"
                >
                  uf
                </Heading>
                <Text>
                  {data?.uf} 
                </Text>
              </Stack>

            </Grid>
          )}
        </Stack>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
